In [1]:
import numpy
numpy.__version__

'1.19.2'

In [2]:
import numpy as np

In [3]:
np?

In [5]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
a.shape

(15,)

In [7]:
a.ndim

1

In [8]:
a.dtype.name

'int64'

In [9]:
a.size

15

In [10]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [11]:

b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

# Day 9 Notes

Applications of Numpy
 - Mathamatics (replacement for MATLAB; Scipy is another option with more mathematical functions)
 - Plotting (Matplotlib)
 - backend of many applications (Pandas, Connect 4, Digital Photography)
 - Machine learning applications (tensors)

In [20]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [13]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [15]:
# get dimenstions
a.ndim

1

In [16]:
# get shape
b.shape

(2, 3)

In [21]:
# get type
a.dtype

dtype('int32')

In [22]:
# get size, value in bytes
a.itemsize

4

In [23]:
# get total size
a.nbytes

12

## Accessing/Changing specific elements, rows, columns, etc...

In [25]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
a.shape

(2, 7)

In [28]:
#get a specific element [row, column]
a[1,5]
#a[1,-2] would give the same value

13

In [29]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [31]:
# getting a little more fancy [start index:end index: step size]
a[0,1:6:2]

array([2, 4, 6])

In [32]:
# replace a single value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [33]:
# replace a whole column
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [36]:
# 3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
# get specific element (work outside in)
b[0,1,1]

4

In [38]:
# replace (must be the same dimension)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [39]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [40]:
# all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# all ones matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [43]:
# any other number, optional to set the dtype
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
#any other number (full_like); reuses a shape that's already built
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
# matrix of random decimal numbers
np.random.rand(4,2)

array([[0.14503714, 0.03338811],
       [0.59790182, 0.24691049],
       [0.52245391, 0.97817607],
       [0.86599988, 0.30051121]])

In [46]:
# random integer values (first parameter is the max (exclusive))
np.random.randint(7, size=(3,3))

array([[4, 0, 1],
       [2, 0, 3],
       [2, 3, 4]])

In [47]:
# generate an identity matrix (always square)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
# practice problem building an array
a2 = np.ones((5,5), dtype='int32')
a2[1, 1:5] = 0
a2[2, 1:5] = 0
a2[3, 1:5] = 0
a2[2,2] = 9
print(a2)

[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 0 9 0 0]
 [1 0 0 0 0]
 [1 1 1 1 1]]


In [57]:
# another solution to build the same array
a3 = np.ones((5,5), dtype='int32')
z = np.zeros((3,3))
z[1,1] = 9
print(a3)
print(z)

a3[1:4,1:4] = z
print(a3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays

In [65]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [66]:
b[0] = 100

In [67]:
print(b)
print(a)

[100   2   3]
[100   2   3]


In [68]:
# an and b are pointing to the same thing
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [69]:
# elementwise arithmetic
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a - 2

array([-1,  0,  1,  2])

In [72]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [76]:
a += 2
print(a)

[ 7  8  9 10]


In [77]:
b = np.array([1,0,1,0])
a + b

array([ 8,  8, 10, 10])

In [78]:
a ** 2

array([ 49,  64,  81, 100])

In [79]:
# take the sine
np.sin(a)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [80]:
# take the cosine
np.cos(a)

array([ 0.75390225, -0.14550003, -0.91113026, -0.83907153])

### Linear Lagebra

In [83]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) # matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [84]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Reference docs (https://numpy.org/doc/stable/reference/routines.linalg.html)

# determinant
# trace
# singlular vector decomposition
# Eigenvalues
# matrix norm
# inverse
# etc...

## Statistics

In [85]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
#find min value
np.min(stats)

1

In [89]:
np.max(stats, axis = 1) # max of each row

array([3, 6])

In [90]:
np.sum(stats)

21

In [91]:
np.sum(stats, axis=0) #sums up each column

array([5, 7, 9])

## Reorganizing Arrays

In [92]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [93]:
#vertically stacking vectors or matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

In [96]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # list of indexes returns specific values

array([2, 3, 9])